// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Szintfelmero.Data;

#nullable disable

namespace Szintfelmero.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251105121459_sqlite.local_migration_821")]
    partial class sqlitelocal_migration_821
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Szintfelmero.Models.orszag", b =>
                {
                    b.Property<int>("orszagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("orszagNeve")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("orszagId");

                    b.ToTable("Orszagok");
                });

            modelBuilder.Entity("Szintfelmero.Models.szakma", b =>
                {
                    b.Property<int>("szakmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("szakmaNeve")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("szakmaId");

                    b.ToTable("Szakmak");
                });

            modelBuilder.Entity("Szintfelmero.Models.versenyzo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("orszagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("pontszam")
                        .HasColumnType("INTEGER");

                    b.Property<int>("szakmaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Versenyzok");
                });
#pragma warning restore 612, 618
        }
    }
}
